package dev.codex.redindiansnight.Event.Domain.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.codex.redindiansnight.Common.Models.AbstractEntity;
import dev.codex.redindiansnight.Event.Domain.ObjectValues.AnswerType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
@NoArgsConstructor

@Entity
@Table(name = "questions")
public class Question extends AbstractEntity<Long> {
    @Id
    @GeneratedValue
    private Long id;

    private String question;

    @Column(name = "is_required")
    private Boolean isRequired = true;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @Enumerated(EnumType.STRING)
    private AnswerType answerType;

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "question")
    @JsonIgnore
    private List<EventQuestion> eventQuestions;

    public Question(String description, Boolean isRequired, Boolean isAutoGenerated, AnswerType answerType) {
        this.question = description;
        this.isRequired = isRequired;
        this.isAutoGenerated = isAutoGenerated;
        this.answerType = answerType;
    }
}
