package dev.codex.redindiansnight.Event.Application.Dtos.Requests;

import dev.codex.redindiansnight.Event.Domain.ObjectValues.AnswerType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

public record QuestionRequest(
        @NotBlank
        String question,

        @NotNull
        Boolean isRequired,

        @NotNull
        Boolean isAutoGenerated,

        @NotNull
        AnswerType answerType
) {
}
