package dev.codex.redindiansnight.Event.Domain.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.codex.redindiansnight.Event.Domain.ObjectValues.AnswerType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
@NoArgsConstructor

@Entity
@Table(name = "questions")
public class Question {
    @Id
    @GeneratedValue
    private Long id;

    private String question;

    private Boolean isRequired = true;

    private Boolean isAutoGenerated = false;

    @Enumerated(EnumType.STRING)
    private AnswerType answerType;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "event_questions",
            joinColumns = @JoinColumn(name = "question_id"),
            inverseJoinColumns = @JoinColumn(name = "event_id")
    )
    @JsonIgnore
    private List<Event> events;
}
