package dev.codex.redindiansnight.Event.Domain.Entities;

import dev.codex.redindiansnight.Event.Domain.ObjectValues.AnswerType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
@NoArgsConstructor

@Entity
@Table(name = "questions")
public class Question {
    @Id
    @GeneratedValue
    private Long id;

    private String question;

    private Boolean isRequired = true;

    private Boolean isAutoGenerated = false;

    @Enumerated(EnumType.STRING)
    private AnswerType answerType;

    @ManyToMany(fetch = FetchType.EAGER, mappedBy = "questions")
    private List<Event> events;
}
