package dev.codex.redindiansnight.Event.Domain.Entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import dev.codex.redindiansnight.Event.Domain.ObjectValues.AnswerType;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Setter
@Getter
@NoArgsConstructor

@Entity
@Table(name = "questions")
public class Question {
    @Id
    @GeneratedValue
    private Long id;

    private String question;

    @Column(name = "is_required")
    private Boolean isRequired = true;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated = false;

    @Enumerated(EnumType.STRING)
    private AnswerType answerType;

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "question")
    @JsonIgnore
    private List<EventQuestion> eventQuestions;
}
